#!/bin/bash

echo "Creating user... Response:"
echo

curl -d '{
  "user": {
    "name": "Keith Norman",
    "first_name": "Keith",
    "last_name": "Norman",
    "username": "keithnorm",
    "id": "124267827",
    "accessToken": "BAAHEY3LOh6IBACD7Ytegu5l0s5Obucb5EcQBhClOtflcJr2b4W9k2tsJLzWGXZAc6gK63zGYKyXw7NqrZAVZBFYjIjABxpHG26ol3uwZAhS5QW5xdxq8cR69ioQZDZD"
  }
}' -H 'content-type:application/json' "http://localhost:3000/api/users"

echo
echo
