#!/bin/bash

echo "Creating user... Response:"
echo

curl -d '{
  "user": {
    "uuid": "12093u198hf13hf39g23hfghidudhs89h1",
    "accessToken": "12nei3b23ygf7gwef79g2fbfdhsg"
  }
}' -H 'content-type:application/json' "http://localhost:3000/api/users"

echo
echo

echo "Creating Promise... Response:"
echo

curl -d '{
  "promise": {
    "userId": "5133c162a56b47492b000001",
    "expiresAt": "Sun Mar 03 2013 13:30:04 GMT-0800 (PST)",
    "description": "Pay Brett money for apartment"
  }
}' -H 'content-type:application/json' "http://localhost:3000/api/promises"

echo
echo